---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-elasticsearch-0
  labels:
    type: local
    app: elasticsearch
    role: data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/u01/elastic_storage/data/0"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-elasticsearch-1
  labels:
    type: local
    app: elasticsearch
    role: data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/u01/elastic_storage/data/1"
