kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-ingest-vol
  labels:
    type: local
    app: elasticsearch
    role: ingest
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/u01/elastic_storage/ingest"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-ingest-claim
  namespace: es
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      app: elasticsearch
      role: ingest
